# Generated by Django 2.2.16 on 2022-02-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220223_1636'),
        ('reviews', '0004_auto_20220224_1600'),
    ]

    operations = [
    ]
